import React from "react";
import { colors } from "../theme";

export interface FileEditorPanelProps {
  /**
   * Element-ID prefix for this panel. Must match the `prefix` passed to
   * `registerFileEditorRoutes` on the server so the client script can wire up.
   */
  prefix: string;
  /** Title shown in the file-list sidebar header (e.g. "Prompts"). */
  title: string;
  /**
   * API base path used to build the script src. The client script is loaded
   * from `${apiBase}/client.js`. Must match the route registration's `apiBase`.
   */
  apiBase: string;
}

/**
 * SSR markup for the standard file editor panel: a left-side file list, a
 * toolbar with filename / dirty / save / status, and a CodeMirror mount
 * point. The behavior is implemented by the client script generated by
 * `registerFileEditorRoutes`.
 */
export function FileEditorPanel({
  prefix,
  title,
  apiBase,
}: FileEditorPanelProps) {
  return (
    <div
      style={{
        display: "flex",
        height: "100%",
        overflow: "hidden",
      }}
    >
      <div
        id={`${prefix}-file-list`}
        style={{
          width: "200px",
          flexShrink: 0,
          borderRight: `1px solid ${colors.border}`,
          display: "flex",
          flexDirection: "column",
          background: colors.surface,
        }}
      >
        <div
          style={{
            padding: "1rem 1rem 0.75rem",
            borderBottom: `1px solid ${colors.border}`,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <h3 style={{ margin: 0, fontSize: "0.9rem", fontWeight: 600 }}>
            {title}
          </h3>
          <button
            id={`${prefix}-new-btn`}
            style={{
              background: "none",
              border: "none",
              color: colors.accent,
              cursor: "pointer",
              fontSize: "1.1rem",
              padding: "0 0.25rem",
              lineHeight: 1,
            }}
            title="New file"
          >
            +
          </button>
        </div>
        <div
          id={`${prefix}-files`}
          style={{
            flex: 1,
            overflowY: "auto",
            padding: "0.5rem 0",
          }}
        >
          <div
            style={{
              padding: "0.5rem 1rem",
              color: colors.muted,
              fontSize: "0.82rem",
            }}
          >
            Loading&hellip;
          </div>
        </div>
      </div>

      <div
        style={{
          flex: 1,
          display: "flex",
          flexDirection: "column",
          overflow: "hidden",
        }}
      >
        <div
          id={`${prefix}-toolbar`}
          style={{
            padding: "0.5rem 1rem",
            borderBottom: `1px solid ${colors.border}`,
            display: "flex",
            alignItems: "center",
            gap: "0.75rem",
            background: colors.surface,
            minHeight: "44px",
          }}
        >
          <span
            id={`${prefix}-filename`}
            style={{
              fontFamily: "monospace",
              fontSize: "0.85rem",
              color: colors.muted,
            }}
          >
            Select a file
          </span>
          <span
            id={`${prefix}-dirty`}
            style={{
              display: "none",
              color: colors.warning,
              fontSize: "0.75rem",
            }}
          >
            (unsaved)
          </span>
          <div style={{ flex: 1 }} />
          <button
            id={`${prefix}-save-btn`}
            style={{
              padding: "0.35rem 0.9rem",
              borderRadius: "0.375rem",
              border: "none",
              background: colors.accent,
              color: "oklch(1 0 0)",
              fontWeight: 600,
              fontSize: "0.8rem",
              cursor: "pointer",
              display: "none",
            }}
          >
            Save
          </button>
          <span
            id={`${prefix}-status`}
            style={{
              fontSize: "0.75rem",
              color: colors.success,
              display: "none",
            }}
          />
        </div>

        <div
          id={`${prefix}-editor`}
          style={{
            flex: 1,
            overflow: "hidden",
          }}
        />
      </div>

      <script src={`${apiBase}/client.js`} defer />
    </div>
  );
}
